version: "3.9"

services:
  app:
    build: .
    container_name: chat-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/chatapp
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mongo
      - redis
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - chat-app-network

  mongo:
    image: mongo:7
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - chat-app-network

  redis:
    image: redis:7
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - chat-app-network

volumes:
  mongo-data:
  redis-data:

networks:
  chat-app-network:
    driver: bridge