apiVersion: v1
kind: Secret
metadata:
  name: chat-app-secret
  namespace: {{ include "chat-app.name" . }}
  labels:
    {{- include "chat-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secret.jwtSecret | quote }}
