name: "argocd"
on :
 workflow_dispatch:
env:
  ARGOCD_SERVER : env.ARGOCD_SERVER
jobs:
 test:
   runs-on: ubuntu-latest
   steps:
     - name : "ArgoCd login"
       run: |
              sudo curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
              sudo chmod +x /usr/local/bin/argocd
              argocd login "${{ env.ARGOCD_SERVER }}" --username admin --password "${{ secrets.ARGOCD_PASSWORD }}" --grpc-web --insecure
              argocd account get-user-info --insecure
  
    
